const baseURL = process.env.REACT_APP_API_URL;
export const urlReactHome = '/';
export const urlReactOrders = '/orders';
export const urlReactScanning = '/scanning';
export const urlOrders = `${baseURL}/api/orders`;
export const urlPart = `${baseURL}/api/orders/part`;
export const urlDrawing = `${baseURL}/api/orders/part/drawing`;
export const urlCsv = `${baseURL}/api/orders/csv`;
export const urlStorages = `${baseURL}/api/storages`;